### ISSUE TITLE
Failing build re _ISO639_TO_BABEL = Babel._ISO639_TO_BABEL.copy()

### ISSUE THREAD

**Issue by rufuspollock** [readthedocs/readthedocs.org#192]
Our build is failing with:

<pre>
Exception occurred:
  File "/home/docs/sites/readthedocs.org/checkouts/readthedocs.org/user_builds/ckan/envs/latest/local/lib/python2.7/site-packages/sphinx/writers/latex.py", line 106, in ExtBabel
    _ISO639_TO_BABEL = Babel._ISO639_TO_BABEL.copy()
AttributeError: type object 'Babel' has no attribute '_ISO639_TO_BABEL'
</pre>

One odd thing I note is that in the install info it states:

<pre>
Installing collected packages: sphinx
  Found existing installation: Sphinx 0.6.4
    Uninstalling Sphinx:
      Successfully uninstalled Sphinx
  Running setup.py install for sphinx
</pre>

Why is it finding an existing Sphinx install? I note that we used to require sphinx 0.6.4 but just changed this -- and last successful build appears to be pre-change (though hard to tell exactly!). We now no longer specify sphinx so should get the default 1.1 ReadTheDocs has (and we build with 1.1 locally without a problem). I have tried wiping that build using http://readthedocs.org/wipe/.../.../ but that has had no effect.

Looking online i've found that this error message may be caused by an incompatibility between sphinx and doc-utils e.g.

http://osdir.com/ml/sphinx-dev/2011-11/msg00035.html

Any help greatly appreciated.
